name: flutter_tiktok_sdk_example
description: Demonstrates how to use the flutter_tiktok_sdk plugin.
version: 1.0.0
publish_to: 'none'
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_tiktok_sdk:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true